create table public.user_info (
    id uuid not null,
    created_at timestamp with time zone null default now(),
    current_period_end timestamp without time zone null,
    customer_id text null,
    plan text null default '' :: text,
    note text null,
    current_period_start timestamp without time zone null,
    constraint user_info_pkey primary key (id),
    constraint user_info_id_fkey foreign key (id) references auth.users (id) on delete cascade
) tablespace pg_default;

create table public.knowledge_base (
    id bigint generated by default as identity,
    uid uuid not null,
    content text not null,
    embedding public.vector null,
    created_at timestamp with time zone null default now(),
    constraint knowledge_base_pkey primary key (id),
    constraint knowledge_base_uid_fkey foreign key (uid) references auth.users (id) on delete cascade
) tablespace pg_default;